ktor:
  deployment:
    port: 8080
  application:
    modules:
      - ru.somarov.gateway.infrastructure.config.ApplicationConfigKt.config
  name: "$APP_NAME:api-gateway"
  instance: "$HOSTNAME:undefined"
  build-props-path: "/META-INF/build-info.properties"
  otel:
    protocol: "http"
    host: "$OTEL_HOST:localhost"
    logs:
      port: "4317"
    metrics:
      port: "4318"
    tracing:
      port: "4319"
      probability: "1.0"
  clients:
    auth:
      host: "ws://localhost:30020/register"
